### ISSUE TITLE
wish for a new gui

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lincity-ng/lincity-ng#1]
```
I d like somthing like this, but it is a rather big job

resolution is 640 x 400 , so it could work even on very small screens


```

Original issue reported on code.google.com by `galba...@gmail.com` on 1 Oct 2011 at 3:11

Attachments:
- [new_interface_commented.png](https://storage.googleapis.com/google-code-attachments/lincity-ng/issue-1/comment-0/new_interface_commented.png)

**Comment by dbear496** [comment]
Closing this because the attachment to the original post no longer exists.
