### ISSUE TITLE
po files out of date?

### ISSUE THREAD

**Issue by rsimai** [lincity-ng/lincity-ng#10]
I was trying (more or less hard) to get the po files (mainly de.po) recreated as explained in doc/translation.txt but failed. It seems I can't properly run the autoconf stuff on my up-to-date openSUSE. The German translations however are incomplete, lots of stuff consequently appears in English.

I'd be happy to help with the translations but that requires someone to update the po files for me, preferably so that I can clone, edit and commit (or send to someone).

Anybody willing to do this?

**Comment by uafr** [comment]
Any error message? On Debian Testing messages.pot files are still generated and I can merge them to the .po files. Probably Suse has a later version of some tools and the incompatibility will hit Debian as well with some delay.

**Comment by rsimai** [comment]
I'm trying to build the application from the repo, as explained in the README to verify if probably only translations in the SUSE package which I use are out of date. I can however not build it.

After installing all dependencies I do autogen.sh, configure and then run jam. This finally pops up the help text from the xgettext.pl as if it's called without or with wrong options. If I end it with "q" I see

robert@big:~/git/lincity-ng> jam
...found 948 target(s)...
...updating 1 target(s)...
XGetText data/locale/messages.pot 
Unknown option: keyword
Unknown option: keyword
...updated 1 target(s)...

Apparently nothing is built. My xgettext.pl comes from a current perl-Locale-Maketext-Lexicon-0.96-4.1.3.noarch package, if that helps. I must say, I'm not familiar with using jam, not sure where to look next...

**Comment by uafr** [comment]
No xgettext**.pl** here. All I have is xgettext (GNU gettext-tools) 0.19.7.

**Comment by rsimai** [comment]
I should have tried harder before my reply, sorry for the noise. I replaced the xgettext.pl with the standard xgettext and indeed it's working :-)
I guess I can translate now.

**Comment by rsimai** [comment]
... and thanks for being with me ;-)
