### ISSUE TITLE
-DLIBXML2_INCLUDE_DIR=/usr/include/libxml2 is ignored

### ISSUE THREAD

**Issue by Mailaender** [lincity-ng/lincity-ng#120]
```
CMake Error in src/gui/CMakeLists.txt:
  Imported target "LibXml2::LibXml2" includes non-existent path

    "/usr/lib/include/libxml2"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

**Comment by dbear496** [comment]
This is likely caused by an incorrect, corrupted, or non-standard installation of libxml2 and not caused by LinCity NG.

Did you remember to install the libxml2 header files? On Ubuntu, these come in the `libxml++2.6-dev` package.

If you installed the header files, what directory were they installed to? You can try linking the `/usr/lib/include/libxml2` location to the directory where the header files were installed.

E.g.
```
sudo ln -s /path/to/libxml2/header/files /usr/lib/include/libxml2
```

**Comment by Mailaender** [comment]
No, this is from building with the official https://freedesktop-sdk.io/

**Comment by dbear496** [comment]
Oh, I see. You are providing the option `-DLIBXML2_INCLUDE_DIR=/usr/include/libxml2` on the command line when configuring (e.g. in `cmake -B build ...`), but that option is being ignored and CMake is still looking in `/usr/lib/include/libxml2`. Is that a fair assessment?

I briefly searched online for documentation about the `LIBXML2_INCLUDE_DIR` variable, and I can't find anywhere that it says this variable can or should be set by the user. It looks like the libxml2 cmake config is setting this variable and thus overwriting the value you give to it.

Unfortunately, I cannot find any documented way to change the default location of libxml2 header files. However, you may try the following:
1) Search for a file on your system named `libxml2-config.cmake`. On my system, this exists in `/usr/lib/cmake/libxml2`.
2) In that file, look for a line of the form `set(LIBXML2_INCLUDE_DIR ...)`
3) Add the `CACHE` option to that line. I.e. `set(LIBXML2_INCLUDE_DIR ... CACHE)`

I don't know why your config file is pointing to the wrong directory in the first place. This may be an issue with LibXml2 or CMake. But I hope this can help you get it working.
