### ISSUE TITLE
Couldn't display dialog 'tradedialog.xml': Couldn't find a component factory for 'Dialog'

### ISSUE THREAD

**Issue by FabioPedretti** [lincity-ng/lincity-ng#122]
version 2.10.1

1. starts Rocket98 map
2. double click on a market

I get:
`Couldn't display dialog 'tradedialog.xml': Couldn't find a component factory for 'Dialog'`

**Comment by FabioPedretti** [comment]
Same issues clicking on ports.

**Comment by dbear496** [comment]
Once again, this was caused by improper `install` directives in `CMakeLists.txt`. Since I most often run the game from the source root without installing, these `install` directives do not get as much testing.
