### ISSUE TITLE
Invalid ExtraFrames at x,y: 87,9 Fire

### ISSUE THREAD

**Issue by FabioPedretti** [lincity-ng/lincity-ng#123]
version 2.10.1

1. starts Rocket98 map
2. set maximum speed and wait for some fires
3. quit the game

I get messages like:
```
Invalid ExtraFrames at x,y: 87,9 Fire
Invalid ExtraFrames at x,y: 87,10 Fire
Invalid ExtraFrames at x,y: 93,15 Fire
Invalid ExtraFrames at x,y: 93,16 Fire
...
```

**Comment by dbear496** [comment]
It looks like this is caused by waste fires. The way waste fires are handled is kinda janky, so maybe it's time to clean that up.

**Comment by dbear496** [comment]
Furthermore, it appears this is only caused by waste fires on track/road/rail. Market waste fires don't seem to trigger this behavior.

**Comment by dbear496** [comment]
This seems to be caused by having two constructions on the same map tile i.e. a track/road/rail and a fire. When destroying the game, only the ExtraFrame for the fire is cleaned up, and the ExtraFrame for the track/road/rail is left dangling.
