### ISSUE TITLE
No windows version in builds 

### ISSUE THREAD

**Issue by Levan7** [lincity-ng/lincity-ng#124]
Have a huge nostalgia to this game and wanted to download this game however noticed there were no Windows version in builds

**Comment by v1993** [comment]
FWIW: on Windows you usually ship libraries with the binary - either as DLLs or via means of static linking. As such, differing library versions are a non-issue if handled properly.

As for aversion - it's much less common for an average windows user to have a build tooling set up than it is for a linux user, and going through the motions of that just to play a single game is too much for many.

**Comment by dbear496** [comment]
Okay, maybe I don't have a full understanding of what it takes to create a binary package for Windows, and perhaps it is easier and more reliable than I thought. And I must agree that building from source, no matter how easy, is more difficult than downloading and running a binary, and most users are accustomed to the latter.

However, I'm still going to need some help if LinCity NG binaries for Windows are ever going to be a thing.

**Comment by nathan130200** [comment]
> It is true; I am not distributing a LinCity NG binary for Windows. One reason for this is I do not have a windows system with which to create such a binary.

@dbear496 Maybe with VCPKG, CMake and CI builds for windows.

**Comment by nathan130200** [comment]
@Levan7 i did an fork will publish for windows. I just made some changes to ensure will correctly execute in windows.

**Comment by Levan7** [comment]
@nathan130200 nathan130200 Marked as a virus when executing

**Comment by nathan130200** [comment]
@Levan7 

Well Windows Defender didnt triggered anything here. I will upload to virus check.

Release version [lincity-ng.exe](https://www.virustotal.com/gui/file/22cfa986318670063fe067dfb927c7c39425e82765de45e74cbb9364828786eb) no detection. Chrome will mark as trojan just because its a unknown source (or file name matched with internal dictionary), no hits.

Debug version [lincity-ng.exe](https://www.virustotal.com/gui/file/5aae532966d628ce5703f8dddb217ec80095d05781f1ddf8976549d42304ec00?nocache=1), one hit because its a Debug (non optimized) compilation.

I'm testing again with MSFT malware check with Debug build, currently not detected anything.

Also you have debug symbols present in both archives to check by yourself.

**Comment by nathan130200** [comment]
Tested debug version in MSFT malware submission, nothing triggered. But again you have all debug symbols present. I just cloned repo, did some small changes in CMakeLists to build correctly in windows.

![image](https://github.com/lincity-ng/lincity-ng/assets/14365254/60b48a17-af7a-4e40-b0a7-53d2d255f9fb)

**Comment by dbear496** [comment]
Due to popular demand, I am learning to cross compile for Windows. To be honest, I expected it to be a lot harder than it was. Would someone mind testing this Windows binary for me?

[lincity-ng-2.10.2-12-g7cf43d7e-win32-test.tar.gz](https://github.com/lincity-ng/lincity-ng/files/15206647/lincity-ng-2.10.2-12-g7cf43d7e-win32-test.tar.gz)

Due to file size limits on GitHub, I am not able to upload a full package, so you will have to get the rest of the files from the Linux package.

**Comment by Levan7** [comment]
@dbear496 Well first got missing ton of dll files well I threw them in but now i got 0xc000007b error something i'm familiar with because dead space wouldn't run on pc had to re install windows and i know that vc is running correctly at least it should because all dead space games run now

**Comment by dbear496** [comment]
@Levan7 Thanks for helping out by giving it a shot. My first thought is _wow, what a descriptive error message._

A quick Google search indicates that this error is often caused corrupt ddl's or by mixing 32 and 64 -bit dll's, so it is possible that one or more of the dll's you "threw in" are causing the issue. Where did you get these dll's from? Are they all 64-bit? Before throwing dll's, did you first install all the dependencies listed in the readme?

I'm not an expert with Windows, but it is possible that you need some form of GNU environment to run the game, so you may need to install something like mingw-w64 or cygwin.

On my end, I may be able to mitigate this issue by statically linking.

**Comment by dbear496** [comment]
Here are the dll's I needed to run the game with Wine. Perhaps it will work if you use these instead of what you "threw in".

[lincity-ng-2.10.2-12-g7cf43d7e-win64-test-exedll.tar.gz](https://github.com/lincity-ng/lincity-ng/files/15209812/lincity-ng-2.10.2-12-g7cf43d7e-win64-test-exedll.tar.gz)

**Comment by dbear496** [comment]
Some of the libraries are not too difficult to link statically: ZLIB, SDL2, SDL2_image, SDL2_mixer, SDL2_ttf, and PhysFS. But SDL2_gfx and LibXml2 are proving to be problematic. Neither have proper Cmake find modules to find the static versions of the libraries, and LibXml2 has internal linking errors when linking statically.

So it looks like I will have to distribute some DLL's with the game -- at least for SDL2_gfx and LibXml2. And if I have to do that, then I may as well distribute all the other DLL's with the game so I don't have bother at all with static linking.

**Comment by nathan130200** [comment]
@dbear496 cross compile in windows is not complicated thing. All hard work CMake already does for you. The only problem i've found in lincity code, its forcing all assets files (musics, etc) in `C:\lincity-ng` folder while building and SDL-gfx is different package in VCPKG, so all packages can be installed from vcpkg.

**Comment by Levan7** [comment]
> Here are the dll's I needed to run the game with Wine. Perhaps it will work if you use these instead of what you "threw in".
> 
> [lincity-ng-2.10.2-12-g7cf43d7e-win64-test-exedll.tar.gz](https://github.com/lincity-ng/lincity-ng/files/15209812/lincity-ng-2.10.2-12-g7cf43d7e-win64-test-exedll.tar.gz)

This worked perfect.
I just downloaded those files from the web (various websites like that, there were multiple dependencies missing) The link work perfectly,
Also i guess if you have 64 bit versions i used 32bit versions so that might have caused it.

**Comment by dbear496** [comment]
@Levan7 That is great news! Though on my end, the sound works fine. (As long as my speakers are plugged in, which I forgot at first lol.) When running from the command prompt, do you see lines like the following?
```
File found: 'music/default/default.xml'. Loading song data...
Found song: 'Robert van Herk - City Blues'
Found song: 'Robert van Herk - Architectural Contemplations'
Found song: 'Pronobozo - Lincity'
```

**Comment by Levan7** [comment]
> command prompt

Well i can start it from CMD but the output is empty but i should point out that there is absolutely no sound not just music no effect sounds

**Comment by dbear496** [comment]
@Levan7 that is very strange that there is no output at all since the very first thing that `main` does is print the lincity-ng version.

**Comment by dbear496** [comment]
Can I get a few more people to test the Windows build? I need some help with this because I do not have a Windows machine myself. You can download it from [this pre-release](https://github.com/lincity-ng/lincity-ng/releases/tag/lincity-ng-2.10.2-26-gb58f3b57).

**Comment by Levan7** [comment]
Hi there tested it on two machines starts without issues music appeases when you bump it up from settings but the sound effects are still missing here is a video that shows it.


https://github.com/lincity-ng/lincity-ng/assets/5770076/6f93dc19-a2ae-449f-84e9-bfea9b856b6e

**Comment by LinaLight** [comment]
Hi, tested on two machines:
1. the 'ja' and 'zh_CN' translations are not displaying correctly.
![无标题](https://github.com/lincity-ng/lincity-ng/assets/63035262/09172142-6a10-4841-961b-25146f2adf0a)
2. There is a thing that confused me for a while: After I switch fullscreen off, everything( except the resolution option ) looks exactly the same as if it's still in fullscreen, you can't even see the taskbar! And I have to reset the resolution each time after i switch fullscreen off.
initial state:
![图片](https://github.com/lincity-ng/lincity-ng/assets/63035262/8bbf77c6-7506-4e6f-a234-b26c642a1be3)
after turn fullscreen on:
![图片](https://github.com/lincity-ng/lincity-ng/assets/63035262/d9ecf41c-108e-4df1-9670-c083531cdba8)
after turn fullscreen off:
![图片](https://github.com/lincity-ng/lincity-ng/assets/63035262/bf39de1a-5815-4645-ad06-e59d6f013887)

**Comment by dbear496** [comment]
@LinaLight thanks for the feedback and the screenshots. I already have a fix for the school/university/port help pages, but I haven't pushed the change yet. I was able to reproduce the window size issue when switching from fullscreen, so I'll work on that. I was also able to reproduce the issue of ja and zh_CN, but this might be an issue with the system font or charset.
