### ISSUE TITLE
Problem with ok_dial_box: Couldn't find a component factory for 'Invention'

### ISSUE THREAD

**Issue by FabioPedretti** [lincity-ng/lincity-ng#125]
version 2.10.1

- starts a new game, builds a monument, then use maximum speed
- a popup appears with an error like `Problem with ok_dial_box: 'cricketup.mes' + ""`

Also, on stdout:
`Problem with ok_dial_box: Couldn't find a component factory for 'Invention'`

**Comment by dbear496** [comment]
This is probably a duplicate of #122
