### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by akien-mga** [lincity-ng/lincity-ng#13]
This repo seems to have some activity, but the last tagged release is 2.0 from 2009.
SourceForge on the other hand, has 2.9.beta from late 2013: https://sourceforge.net/projects/lincity-ng.berlios/files/?source=navbar

That's the version that most Linux distros package, but if this git repo is more up to date, it would be great to have this reflected in the tagged releases.

**Comment by uafr** [comment]
Tag lincity-ng-2.9-beta added.

**Comment by akien-mga** [comment]
Thanks :)
