### ISSUE TITLE
Pop-up windows are too small on high resolution screen

### ISSUE THREAD

**Issue by FabioPedretti** [lincity-ng/lincity-ng#131]
The current window size, for example the Help windows, may be OK on a 1024x768 resolution, but is too small on a current screen resolution (with common resolution of 1920x1080), forcing the player to scroll to read all the content.

Eventually, when using a resolution of 1920x1080 and the content inside not fitting in the actual window size, the window size should be made bigger.

Also, when the content fits in the current window, the scroll bar should not be shown.

**Comment by dbear496** [comment]
The help window size is set to 500x400 no matter the size of the screen or game window, and I think it looks fine on a 1920x1080 display. There is plenty of extra space that is not used by the help window, and this is helpful for dragging the window to the top left corner and poking around the game while the help window is open. It would be nice to allow the player to drag the edges/corners of the window to resize it, but for now while the window size is static, I think 500x400 is fine even on a 1920x1080 display.
