### ISSUE TITLE
1 MWh = 1000 kWh according to common sense, but it's 2 kWh in game?

### ISSUE THREAD

**Issue by apricot-azumi** [lincity-ng/lincity-ng#134]

**Comment by dbear496** [comment]
I agree, this is an odd quirk about the game. Perhaps the two types of power should be renamed to be more logical. Maybe the they can be distinguished by high vs. low voltage.

**Comment by dbear496** [comment]
With a lack of input from anyone else, I've decided to rename "MWh" to "high-voltage power" and "kWh" to "low-voltage power". In places where a short name is preferred, "hi-volt" and "lo-volt" can be used. This rename will have to occur throughout the help files. I noticed the GD translation of the help files uses the "MWh" and "kWh" strings, so those may need to be translated properly.
