### ISSUE TITLE
copyright years in main menu background not updated

### ISSUE THREAD

**Issue by FabioPedretti** [lincity-ng/lincity-ng#148]
The main menu background game image shows copyright years of 2004-2009, here are the svg and png files:
https://github.com/lincity-ng/lincity-ng/blob/master/data/images/mainmenu/menu_back.svg and https://github.com/lincity-ng/lincity-ng/blob/master/data/images/mainmenu/menu_back.png
I suppose the svg could be updated easily, and then converted to the png.

Given the game is being developed again now (thanks! ❤️) it should show updated years, even better I would propose to completely remove that line from the image, and add the years into the Credits menu.

**Comment by dbear496** [comment]
Nice catch. I should probably also update the copyright years in the source file headers and add license headers to all the new files.
