### ISSUE TITLE
How to build now?

### ISSUE THREAD

**Issue by brianmaher84** [lincity-ng/lincity-ng#15]
It seems the project doesn't have much activity.

I tried to clone the repo and build from source on OSX but I cannot run the configure command.

I can build against the old sourceforge version of the project but would like the latest code to do the build.

Is there something I'm missing.  I've built other projects from source without issues before and use Cygwin quite regularly in work but can't see how I can build this project.

When I go to osx dir and run build.sh, it tells me I should run configure first.

    Brians-MBP:lincity-ng brianmaher$ ls
    Bugs-beta		Jamfile			README-WaterWell	configure.ac		lincity-ng.desktop	 src
    COPYING			Jamrules		RELNOTES		contrib			makerelease.sh
    COPYING-data.txt	README			TODO			data			mk
    COPYING-fonts.txt	README-Unlimited	autogen.sh		doc			osx
    Brians-MBP:lincity-ng brianmaher$ ./configure
    -bash: ./configure: No such file or directory

Thanks

Brian.

**Comment by uafr** [comment]
If you got the source from git you have to run ./autogen.sh first. Afterwards ./configure and jam
No idea if that helps on OSX.

**Comment by brianmaher84** [comment]
I did try that after reading about it before posting but it just lead to other errors.
When I ran ./autogen.sh I got the following message:
    Brians-MBP:lincity-ng brianmaher$ ./autogen.sh 
   ./autogen.sh: line 9: aclocal: command not found
   ./autogen.sh: line 10: autoheader: command not found
    ./autogen.sh: line 13: autoconf: command not found
   ./autogen.sh: line 21: autoconf: command not found

**Comment by brianmaher84** [comment]
ok I ran brew install automake and it resolved those errors.

**Comment by brianmaher84** [comment]
I have been able to compile but once I run I just get a black screen.

The relevant message on command line says:
    Starting lincity-ng (version 2.9.beta)...
    Couldn't add '/Users/brianmaher/Downloads/lincity-ng/Contents/Resources/share/lincity-ng' to  physfs searchpath: File not found
    [/Users/brianmaher/.lincity-ng] is in the search path.
    [/Users/brianmaher/Downloads/lincity-ng/data] is in the search path.
    [/Users/brianmaher/.lincity-ng] is the write directory.

**Comment by brianmaher84** [comment]
ok I have it running.  I used the ./osx/build.sh script.

Afterwards, I got a white screen.  I modified the file to the below:
<?xml version="1.0"?>
  2 <configuration>
  3     <video x="1024" y="768" useOpenGL="no" fullscreen="no" restartOnChangeSc    reen="yes" />
  4     <audio soundEnabled="yes" soundVolume="100" 
  5            musicEnabled="yes" musicVolume="50"
  6            musicTheme="default" />
  7     <game quickness="10" language="autodetect" WorldSideLen="50" binarySaveG    ames="yes" seed_compression="yes" carsEnabled="yes" />
  8 </configuration>

Everything is no working and it runs in window which I prefer.

**Comment by brianmaher84** [comment]
Is there a way for me to package this working sound version for other users?  Or is it just compiled for my machine?

I can take the libs folder from the bintray with the dependencies and just add it to the generated .app file I have?

If I upload that will it work on other OSX machines?  At least it should work on OSX Sierra machines right?

**Comment by GammaNu** [comment]
How about using [Travis](https://docs.travis-ci.com/user/languages/cpp/) or something like that to auto build tagged release, or nightly from master branch ?

**Comment by jpenguin** [comment]
@brian- run otool -L to make sure the executable only links to standard or included libs

**Comment by jpenguin** [comment]
The build.sh script used to give a distributable DMG, I wrote that script, but don't use OSX anymore; so I can't really update it.  Sound worked fine back then

**Comment by janni2** [comment]
Hi I randomly stubled on this project and that issue. I follwed the instructions like guessing the packages via
`apt-cache search physfs`
then run
`sudo apt-get install build-essential git  libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-gfx-dev  libphysfs-dev zlib1g-dev libxml2-dev autoconf`
`git clone https://github.com/lincity-ng/lincity-ng.git`
Running `./autogen.sh` told me to make an autoupdate before.
Then as described `./configure' and 'jam`
It compiled successfully on Windows with Ubuntu WSL2 machine and it even started, just resolution looks a bit odd.
