### ISSUE TITLE
House desirability become sometime highly negative

### ISSUE THREAD

**Issue by FabioPedretti** [lincity-ng/lincity-ng#151]
Just monitor desirability of a house, it usually varies a bit (for example around  45 - 50).
However it also has some highly negative spikes (for a fraction of second), for example to -215, as can be seen on this screenshot:
![desiderability-negative](https://github.com/lincity-ng/lincity-ng/assets/3390837/bdb9f9f5-a099-4181-9d37-7a09cad47662)

I still don't fully well understand the game mechanics, but it seems strange to me...

**Comment by dbear496** [comment]
Negative desirability like that usually means residents are dying -- either from starvation or pollution.

In your screenshot, I can see that the residence has only 3.2% food inventory, which is extremely low. I can also see that your Eco tab is red, which means there is starvation. Try building more farms, and make sure your farms have enough labor.
