### ISSUE TITLE
[question] Why not use std::fstream?

### ISSUE THREAD

**Issue by bufalo1973** [lincity-ng/lincity-ng#154]
I've looked thru the code and all file management is based on FILE. Why not use std::ifstream and std::ofstream? I don't know if that can be done 100% but I find it easier to use than using pointers, fprintf, ...

**Comment by uafr** [comment]
Historical reasons. That code was working ~30 years ago, why change it?

**Comment by bufalo1973** [comment]
I think (maybe I'm wrong) that getting rid of pointers (and their management) is a good idea. And I find clearer the way std::fstream works.

But it was just a question.

**Comment by bufalo1973** [comment]
As of today, only 2 files use FILE:
- src/lincity-ng/MainLincity.cxx: to find if a file exists.
- contrib/render/autocrop.cxx: loading a PNG. Can be replaced by IMG_Load

**Comment by dbear496** [comment]
This project uses PhysFS for filesystem access. So any use of `FILE` is incidental and not systematic.
