### ISSUE TITLE
New building available message, but it was already available and it is no longer available

### ISSUE THREAD

**Issue by FabioPedretti** [lincity-ng/lincity-ng#165]
- run good times scenario
- note Solar Power Plant are available to be built
- set maximum speed
- note the decreasing Tech level
- as soon as the Tech level decreases under 50 (around year 700) you get a Solar Power Station available message
- note Solar power stations are no longer available to be built

Note it's not specific to Solar Power Plants, I saw similar behavior with Recycling Center.

Possibly for another bug: if you have already selected the building of a Solar Power Plant before Tech goes under 50, you can still build them, but if you change the building type you cannot select them anymore. Maybe the availability check should be done before placing the building, not only when selecting it from the menu.

**Comment by dbear496** [comment]
Both these issues should be fixed in #191. The game was actually already _trying_ to check tech before placing a building, but it was comparing a normalized tech level to an unnormalized tech level, so you'd be able to build solar power stations as long as you were above 0.05 tech LOL.
