### ISSUE TITLE
segmentation fault while bulldozing

### ISSUE THREAD

**Issue by FabioPedretti** [lincity-ng/lincity-ng#182]
- using current git
- start Rocket_98 map
- zoom out to see all the map
- select Bulldoze tool
- keep the mouse button pressed and bulldoze everything (click yes to the messages, or just ignore them, you can continue bulldozing anyway)
- after a while the game segfaults

**Comment by dbear496** [comment]
Oddly, it doesn't seem to segfault in the same place every time. The really annoying part is if I capture the segfault in a debugger, then my mouse is not released from the game window, making it difficult to operate my computer.

**Comment by dbear496** [comment]
So it seems `GameView` doesn't check that the cursor is inside the map before calling `check_bulldoze_area`. This seems to only be a problem when dragging since `editMap` is used for regular clicks.
