### ISSUE TITLE
Light Industry is Bugged.

### ISSUE THREAD

**Issue by WestEastNorth** [lincity-ng/lincity-ng#200]
For some reason only one light industry consistently takes advantage of the 4 times boost that comes with electrification. The rest cannot really enjoy the boost so only one Light Industry at all times will be able to get 100% productivity. Not sure what causes this. 

I figure the root cause is somewhere in light_industry.cpp with
"int total_power_p_good = (commodityCount[STUFF_LOVOLT] + 2 * commodityCount[STUFF_HIVOLT]) / (4 * goods_today);
        if ((total_power_p_good >= INDUSTRY_L_POWER_PER_GOOD)
         && (commodityCount[STUFF_ORE] >= INDUSTRY_L_ORE_USED)
         && (commodityCount[STUFF_GOODS] + 4 * goods_today <= MAX_GOODS_AT_INDUSTRY_L))"
Could be total_power_p_good or the MAX_GOODS_AT_INDUSTRY_L check. I noticed this behavior when I started to individually remove light industries and noticed every time only one could get 100% output despite an abundance of power.

**Comment by dbear496** [comment]
Light industry is rather complicated. In order for light industry to take advantage of the 4x production with power, you must have all of 1) plenty of power, 2) extra ore, and 3) plenty of space to store the produced goods. My top guess is that your light industries are saturated with goods so there is not enough space to produce extra. To solve this, you can improve your transport, spread your light industry units around the map, delete some light industry units, and/or settle for less than 100% busy light industries.

Feel free to re-open this issue if this doesn't explain what you are seeing. Some screenshots would be helpful if you think this is truly a bug.
