### ISSUE TITLE
Update to the PhysFS 3.0.0 API

### ISSUE THREAD

**Issue by queengooborg** [lincity-ng/lincity-ng#25]
Lincity-NG isn't compatible with PhysFS 3.0.0.  Every time I attempt to launch it, I get an error: `Unexpected exception: Failed creating configuration directory '/Users/vinyldarkscratch/.lincity-ng': unsupported`  To the extent of my knowledge, this didn't happen on earlier versions of PhysFS.

**Comment by Mappaschreck** [comment]
If you start Lincity-NG instead of a directory a file .lincity-ng was made.
Just delete the file and create the directory .lincity-ng on your own.

**Comment by uafr** [comment]
Physfs should be working as expected again with libphysfs 3.0.2
https://hg.icculus.org/icculus/physfs/rev/a29fef4a20fd

**Comment by dbear496** [comment]
From what I gather, this was caused by a bug in PhysFS which has since been fixed. If you are still experiencing this issue after updating PhysFS and deleting the `~/.lincity-ng` *file*, then feel free to reopen this issue.
