### ISSUE TITLE
City income suddenly goes into the red

### ISSUE THREAD

**Issue by wimsett67** [lincity-ng/lincity-ng#28]
Hello,

I have played this game countless times with the same results.  I have a cash income of over 20 million, and when I reach around year 1356 or so the positive 20m income suddenly becomes negative and remains there going further into the negatives.  The first thing to go wrong relatively early on is that the power mega watts suddenly stop working and remain on 0% until a year or two before the negative income bug comes in.  At this time it jumps to a positive result in the thousands and then jumps to a slightly less amount in the negatives.

The other issue is that there seems to be a hard coded maximum amount that the city can produce.  It seems to be around the 200 billion mark and no matter what it will not budge past that amount.

Please not that I have not run out of resources as I deliberately choose an extra large map and the coal and ore reserves are well in hand.  My tech level is around the 300 mark.  Also when you reach the billions, in the stats box it shows as 1.2G.  What the hang is that about?  Should it not be 1.2B?

Can these issues be fixed or has this project actually totally died?

Regards,

Christopher.

**Comment by uafr** [comment]
Without looking at the source I assume that G is used for Giga (10^9).

The real issue is the overflow which has to be fixed somehow. I'm not sure if it's feasible to use a bigger data type but at least prevent the overflow and keep the money at maximum instead of jumping to negative.

**Comment by wimsett67** [comment]
Thank you for your reply to this.

I need to clarify that I am playing this game on linux (www.linuxfromscratch.org).

I have played this game a number of ways.  From what I have observed when playing, it is next to impossible to get everyone evacuated in space ships due to the fact that that you need bucket loads of cash to create the ships.  By the time you have built the game to over the 100 tech level, and built up the funds you end up getting into a catch 22 situation.  Firstly, by the time you have successfully launched two or three rockets at the same time with people aboard, your income seriously dips even to the point of negative if you have not built enough funds.  By the time the funds have recovered the resources are getting low, and the population has increased back to the point of pre-evacuation.

From what I can see, and I could well be wrong on this point, you have to have the income level constantly going up to such a point where you can have say 60 or more rockets being built at the same time so that they are all ready to launch and then launch them immediately evacuating everyone at the same time and hence winning the game.  No matter what the map size is, eventually you are going to run out of resources.  

I love this game as it really does pose challenges.

Regards,

Christopher.

**Comment by dbear496** [comment]
I believe this issue is fixed in beba82669b23660bf6a1c066e9852004e3b7755a, which is from 2005. You must be using an old version. If you still experience this issue in the current version, then feel free to reopen the issue.
