### ISSUE TITLE
Unable to see cursor/pointer

### ISSUE THREAD

**Issue by OldKingSol** [lincity-ng/lincity-ng#29]
I'm unable to see the cursor/mouse pointer. I can see the land is highlighted, and I could navigate that way fine. But when it comes to interacting with menus, no mouse pointer makes it virtually impossible. Is there a setting I'm missing or something? Any help would be appreciated, I used to play this game a lot and really enjoyed it. Thanks for your time. :-)

**Comment by uafr** [comment]
Which version of Lincity do you use? Anything in stderr.txt or stdout.txt? No idea where Windows 10 puts these files,on older Windows versions they are in the same folder as the binary but I think current Windows redirects that to some other place.

**Comment by OldKingSol** [comment]
Thanks for replying! :-) I found both of these files. The stdout.txt appears to be empty (0 bytes, no text when I open it), but the stderr.txt only has one line:
 fast = 9

**Comment by OldKingSol** [comment]
(It's in the c:/Program Files (X86)/LinCity-NG directory)

**Comment by OldKingSol** [comment]
It says it's LinCityNG 1.97 beta.

**Comment by jpenguin** [comment]
AFAIK The latest windows version is 2.0, you can download it from sourceforge or bintray https://bintray.com/lincityng/LinCity-NG/LinCity-NG/2.0#files
Linux/OSX have 2.9 beta, I don't think anyone compiled it on windows

On December 29, 2017 4:58:27 PM PST, OldKingSol <notifications@github.com> wrote:
>It says it's LinCityNG 1.97 beta. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lincity-ng/lincity-ng/issues/29#issuecomment-354518532

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by OldKingSol** [comment]
Thanks, uninstalled the old completely, even deleted the folder. Installed the new, and it's the same issue. :-/ I really appreciate your responses, but this one may not have a solution. Thanks for trying, though.

**Comment by dbear496** [comment]
Since this issue was opened, the project has migrated to SDL2 (d35c3bee434900deedd610b7b08a9bd8504e4c41), which would likely fix an issue like this. So I will close this issue for now; if you still experience this issue in a recent version, then please re-open this issue or open a new issue.
