### ISSUE TITLE
Game starting error when 2 monitors attached

### ISSUE THREAD

**Issue by psypherium** [lincity-ng/lincity-ng#32]
With two displays attached, upon starting lincity-ng, my secondary display will start to show 'input not supported'.

After waiting a short time, the primary display becomes corrupted, requiring a system reboot.

Unplugging the secondary monitor and booting the game works correctly.

Arch Linux, AMDGPU, Mesa 18

**Comment by uafr** [comment]
Which version of Lincity do you use? 
Is it windowed mode or fullscreen?
Can you capture the console output to stdout/stderr? It might contain some hints what went wrong.

**Comment by psypherium** [comment]
This problem occurs on the regular build and the git build. It is set to fullscreen I think. Running  "lincity-ng >out 2>&1" creates a file which says "fast = 10"

It may have something to do with 1440p resolution, if I run the game with one monitor and successfully close the game, running again with both monitors attached will display ane half of the picture on each screen.

If I then delete "userconfig.xml" and try running again, it will freeze the system.

**Comment by uafr** [comment]
I managed to try Lincity on a dual head setup. While it did not freeze my system switching resolutions in fullscreen mode crashes the game or messes up screen resolution and location. Running Lincity in gdb causes internal gdb problems.

Workaround would be to play in windowed mode. To switch to windowed mode if you can't reach the option menu you can use command line option "-w" or "--window" to do so. 
Maybe we should use windowed mode as default to cause less problems?

**Comment by dbear496** [comment]
I have had no trouble using fullscreen with two monitors in the current version on ArchLinux. I think this was likely fixed by the migration to SDL2, which came in 2021. If you still experience the issue in the current version, then please re-open the issue.
