### ISSUE TITLE
Floating point exception when first run

### ISSUE THREAD

**Issue by andy5995** [lincity-ng/lincity-ng#37]
This happens on the git version that I built.

Game crashes with the message "Floating Point exception" in the terminal if "Map size" isn't changed in the options to a value > 0.

* OS: Debian buster

## To reproduce

* remove existing config file
* start lincity-ng
* click new game
* select "temperate"
* click start

It looks like there's a check at https://github.com/lincity-ng/lincity-ng/blob/72f4660b230f9ba0e34835f78c4b62eea1e3d785/src/lincity-ng/Config.cpp#L141 but I'm not sure what else is needed.

**Comment by sanbeg** [comment]
This issue also happens with the version in the Linux Mint 20 repository..  When installed from synaptic the map size defaults to 0, and the game crashes on startup unless you find and change that setting.

**Comment by jbrepogmailcom** [comment]
Same problem here. Just installed it but does not work. PRETTY_NAME="Ubuntu 22.04.1 LTS"
