### ISSUE TITLE
Use SDL2

### ISSUE THREAD

**Issue by v1993** [lincity-ng/lincity-ng#39]
Lincity-NG currently use SDL1.2, which is outdated and should be replaced by SDL2.

I see that Lincity-NG isn't currently being worked on, it it no longer maintained?

**Comment by andy5995** [comment]
Seems like it's still being maintained. The last commit was as recent as 2 months ago.

**Comment by heikkiket** [comment]
Well, not really. In last two years there has been five commits to the repository, most of them translation updates. Modifications that touch the actual source code from last two years sum up to five lines. So pretty much unmaintained project.
