### ISSUE TITLE
Request for archive or copies of Lincity-ng documentation (from Berlios.de)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lincity-ng/lincity-ng#4]
```
Berlios.de (before closing) held a significant amount of documentation for 
Lincity-ng (including the very important Formulas page). Many useful pages of 
information, tutorials, tips, and formulas are now missing, and would 
drastically help players both expert and new.

If possible, is there a way to get that documentation (or at least that one 
important page) back? Does anyone have a copy of it or know a site that might 
have mirrored or backed up the Berlios wiki for Lincity-ng?
```

Original issue reported on code.google.com by `BattleCo...@gmail.com` on 9 Nov 2014 at 5:11

**Comment by asl97** [comment]
clickable links from above:
http://web.archive.org/web/20111130170931/http://lincity-ng.berlios.de/wiki/index.php/New_game
http://web.archive.org/web/20111130182910/http://lincity-ng.berlios.de/wiki/index.php/Formulas

@uafr why don't you upload that dump somewhere?   someone might be able to come up with something.

**Comment by uafr** [comment]
The dump contains user data like email addresses and password hashes so I really don't want to upload it for general public.

**Comment by dbear496** [comment]
FWIW, I created some notes that contain a lot of the same information that is in the formulas page. I agree that this information would be useful to have in the in-game help.

[lincity-ng_notes.txt](https://github.com/lincity-ng/lincity-ng/files/13759957/lincity-ng_notes.txt)
