### ISSUE TITLE
Simple Dunno

### ISSUE THREAD

**Issue by inukaze** [lincity-ng/lincity-ng#44]
Hi there, i just want to ask :
¿Lincity-NG can use SimCity 3000 Unlimited Data?

**Comment by phosit** [comment]
I don't know what kind of Data you mean, but i don't think so.

**Comment by inukaze** [comment]
> I don't know what kind of Data you mean, but i don't think so.

The GameData of Sim City 3000 Unlimited [The files when the game is installed on a Hard Disk Drive, for the people can use for play the game]

**Comment by rodneyrod** [comment]
No, there is no support with Simcity 3000 or any other version

**Comment by inukaze** [comment]
Thanks for the information :)
