### ISSUE TITLE
[Feature request] Volunteer language support (Greek, Esperanto, or Korean)

### ISSUE THREAD

**Issue by seanpm2001** [lincity-ng/lincity-ng#46]
***

### [Feature request] Volunteer language support (Greek, Esperanto, or Korean)

I am interested in this game, and I would like to help contribute to it. I don't think I would be able to help with the programming, since I am not experienced with the languages used, but I could try to add some locale support.

I can do some translations for any language, I was thinking either Greek, Esperanto, Korean, or all 3 (they are ones with millions of native speakers) it wouldn't increase the size too much, I estimate it would only increase by 102-180 kilobytes. Any translation errors can be fixed by native speakers, as I will be using a translating service. I would like to take a try at adding support for these languages (Greek: EL | Esperanto: EO | Korean: KO)

I can do other languages if you want as well.

If @uafr or any of the other trusted contributors are OK with this, I will try to do so later today, tomorrow, or any time within the next 7 days. This will be my first external GitHub contribution if I have permission.

Thank you for your time - SeanPM

***

**Comment by seanpm2001** [comment]
I just noticed: this project hasn't been active for 14 months. @uafr do you have any interest in resuming this project?

**Comment by uafr** [comment]
Greek translation is already included. No idea how complete it is at the moment. Not
really sure if machine translation is the way to go. At least for languages I understand
the results were not too convincing.

**Comment by seanpm2001** [comment]
OK. Thank you for the response.
