### ISSUE TITLE
Lincity-ng crashes frequently

### ISSUE THREAD

**Issue by Weolvi** [lincity-ng/lincity-ng#52]
Hi, this is my first post to Github and thus also my first post to Lincity. I have loved this game since I first found it packaged with a Linux distro about two decades ago. Even though it now is way better with the fancy graphics and all, it frequently crashes on me which makes it pretty much unplayable.

This has not just started now, but already a couple of years ago and with different distributions. According to the package name, the current version on Ubuntu 20.04 seems to be compiled from a Github version of 2015. So I thought that maybe all issues have been solved and downloaded a fresh copy from Github to compile the game by myself.

That worked rather uneventful (even though I wonder why jam recreates all the files every time you invoke it -- make was smarter in that respect...). However, Lincity-ng still crashes. So I recompiled a non-optimized debugging version and waited for the first core to be dumped.

I am neither good with gdb nor do I know C++ very well, so all I can do is to show you the output of the where command and kindly ask you to look into this issue. The core is still there, so I can run additional debug commands to give you more information if needed.

(gdb) where
#0  0x00005608d4eaaf85 in std::_List_const_iterator<ExtraFrame>::_List_const_iterator(std::_List_iterator<ExtraFrame> const&)
    (__x=<error reading variable: Cannot access memory at address 0xb8>, this=<optimized out>) at /usr/include/c++/9/bits/stl_list.h:284
#1  Transport::update() (this=0x5608d7667530)
    at src/lincity/modules/track_road_rail.cpp:174
#2  0x00005608d4e828a4 in simulate_mappoints () at src/lincity/simulate.cpp:291
#3  do_time_step() () at src/lincity/simulate.cpp:118
#4  0x00005608d4e287c5 in execute_timestep() ()
    at src/lincity-ng/MainLincity.cpp:75
#5  0x00005608d4e59dd5 in Game::run() (this=0x5608d73f1540)
    at src/lincity-ng/Game.cpp:308
#6  0x00005608d4e26ca9 in mainLoop() () at src/lincity-ng/main.cpp:338
#7  0x00005608d4dfef87 in main(int, char**) (argc=1, argv=0x7ffd7be5b758)
    at src/lincity-ng/main.cpp:492
(gdb)

**Comment by Weolvi** [comment]
Not much going on around here...
Anyway, despite the crashes I kept playing and made the following additional observation: I noticed that the crashes are related to excess waste being burned. Previously, I have accepted that and simply built the residential areas up-wind as mitigation. But since I started using tips, the crashes are practically gone. I hope this information helps.

**Comment by demotomohiro** [comment]
According to the comment of https://github.com/lincity-ng/lincity-ng/pull/51, it fixed:
> Fires from waste burning ("waste" fires) caused intermittent segfaults because the game tries to delete them twice.

That PR was merged to master recently.

Do you still get the crash on latest master branch?
