### ISSUE TITLE
Saved game doesn`t load.

### ISSUE THREAD

**Issue by Veatrix** [lincity-ng/lincity-ng#59]
1. Open the game.
2. Choose "Continue" or "Load" (at Load choose the game).
3.  See descktop.

This issue occurs at 90% or close to that.
My OS: Fedora 36

**Comment by Veatrix** [comment]
Only this on therminal: 
чер 04 14:14:24 veatrix abrtd[943]: Size of '/var/spool/abrt' >= 5000 MB (MaxCrashReportsSize), deleting old directory 'ccpp-2022-06->
чер 04 14:14:25 veatrix abrt-notification[3926]: [🡕] Process 3823 (lincity-ng) crashed in ??()

Version of game is the same and it is installed from Dolphine, which told me that it is 2.9-0.27.20210424gitd35c3be.fc36.

**Comment by fyrefiend** [comment]
I'm having the same issue.
Version: lincity-ng version 2.9.beta
OS: Debian 12

When run from terminal it crashes when loading the save with 
`gz loading /home/fyre/.lincity-ng/1_Y00010_Tech000_Cash+022K_P00425.gz ... [1]    107949 segmentation fault (core dumped)  lincity-ng`

Attached is the coredump

[core.gz](https://github.com/lincity-ng/lincity-ng/files/12255348/core.gz)

**Comment by dbear496** [comment]
Would someone mind providing a save file that causes the crash? I want to see whether this is still an issue in the most recent version.
