### ISSUE TITLE
feature request : modding API

### ISSUE THREAD

**Issue by tigercoding56** [lincity-ng/lincity-ng#61]
it would be nice to have a modding API for adding new buildings , tiles , resources   and similar 
preferably in a pythonic language    so it is easier for new players to understand

**Comment by dbear496** [comment]
This might be a cool feature. However, I do not think it adds to the current play experience. It would also be impossible to balance the difficulty of the game with a feature like this. I expect that people would make a OP constructions and turn the game into easy mode.
