### ISSUE TITLE
CMake + Vcpkg + GitHub Actions

### ISSUE THREAD

**Issue by Arcnor** [lincity-ng/lincity-ng#76]
Hello,

Over at https://github.com/ReversedGames/lincity-ng/ I've forked this repository (actually forked from @dbear496) and I've replaced Jam / autotools with CMake, but I've also added vcpkg (https://vcpkg.io) to automatically deal with the dependencies, as well as added a CI run (on GitHub Actions) that builds and packages the game, you can see the last build and artifacts at https://github.com/ReversedGames/lincity-ng/actions/runs/3942624490 if it hasn't expired yet.

Currently no I18N generation is done, and the `LINCITY_HOME` detection is not there either, but those should be easy to add by anybody interested, this is the bare minimum to modernize the build system. Also, Linux and macOS builds are untested.

I understand the game is unmaintained, so not sure if a PR will do any good as I've seen many outstanding ones, but just in case anybody is interested (like the people commenting at issue #36 or any of the other Jam ones) they can take a look at my fork.

Thanks to all the people working on the game for all these years, it's a surprisingly solid one.

Update: I've also added some code to regenerate XML GUI files when changed and added them as part of the build.

**Comment by dbear496** [comment]
Hey, thanks for contributing. I took a look at your changes, and I have a few comments.

I especially like the switch from Jam to CMake. Jam is old, no longer maintained, and the original source code repository is down, and it has an annoying bug in ArchLinux that causes incremental builds to take a long time.

I've never developed with CMake, vcpkg, or GitHub Actions, and this is the first time I've heard of vcpkg. So I'll have to learn how to use those before I assess changes related to them. Though I will say that I'm already not a big fan of vcpkg since I try to keep Microsoft off my machine (just a pet peeve of mine).

- I noticed you use `SDL_strcasecmp`; however, I cannot find any API documentation for this, so I'm not sure it is supported in SDL 2.0.0 or even whether it is public API. The source code shows it is just an alias for `strcasecmp`, so I'm unsure why you want to use it.
- In Event.cpp, you ignore `HAVE_SDL_MOUSEWHEELEVENT_MOUSEX` and go ahead and use `event.wheel.mouseX` and `event.wheel.mouseY`, but the `mouseX` and `mouseY` members were added in SDL 2.26.0 and do not exist in SDL 2.0.0. Since the minimum supported version of SDL is 2.0.0 according to the readme, we must use an alternative if the `mouseX` and `mouseY` members do not exist.
- Please do not add `.idea` to .gitignore, since not all of us use the same IDE. Instead, you can add that directory to your global .gitignore (probably ~/.gitignore). See [this blog post](https://blog.martinhujer.cz/dont-put-idea-vscode-directories-to-projects-gitignore/) for a discussion on the topic.

**Comment by Arcnor** [comment]
> I especially like the switch from Jam to CMake. Jam is old, no longer maintained, and the original source code repository is down, and it has an annoying bug in ArchLinux that causes incremental builds to take a long time.

Yeah, that was one of the main reasons for my change. CMake is not perfect, but it's the *de facto* build system in C++, so it makes sense to move to it. There are up and coming alternatives like Meson, but the tooling and community is simply not there at the moment.

> I've never developed with CMake, vcpkg, or GitHub Actions, and this is the first time I've heard of vcpkg. So I'll have to learn how to use those before I assess changes related to them. Though I will say that I'm already not a big fan of vcpkg since I try to keep Microsoft off my machine (just a pet peeve of mine).

That's fair, but for package managers there are only 2 real choices: Conan and vcpkg, with the latter having a strong connection to CMake, which can be good or bad, but in this case I prefer that against having to learn Python (which is what Conan does) to write the build files (also no need to use special plugins in my IDE to use, because it's just CMake).

As mentioned in the README, you can use it if you want, but you're not forced to. This was done mainly for personal usage, as well as for ease of use & consistency in the CI build (same & updated versions between OSes, etc).

> * I noticed you use `SDL_strcasecmp`; however, I cannot find any API documentation for this, so I'm not sure it is supported in SDL 2.0.0 or even whether it is public API. The source code shows it is just an alias for `strcasecmp`, so I'm unsure why you want to use it.

`SDL_strcasecmp` has been there for at least 10 years and it's part of the `stdinc` subset SDL implements. Whatever it does internally I don't really care, but `strcasecmp` is not standard C++ (it's POSIX AFAIK), so it's not part of some compilers and an alternative is needed. It can be changed to anything else if you want, but given that SDL gives the convenience, I don't see a good reason to.

> * In Event.cpp, you ignore `HAVE_SDL_MOUSEWHEELEVENT_MOUSEX` and go ahead and use `event.wheel.mouseX` and `event.wheel.mouseY`, but the `mouseX` and `mouseY` members were added in SDL 2.26.0 and do not exist in SDL 2.0.0. Since the minimum supported version of SDL is 2.0.0 according to the readme, we must use an alternative if the `mouseX` and `mouseY` members do not exist.

Thanks, I forgot to put this back as I was testing it, although instead of adding a very specific define for it I think we should just test for the SDL version used to compile it, there is a handy macro I can use for this so I'll make that change. Also, I'm sure the readme is outdated at this point, SDL 2.0.0 was released in 2013 and I'm sure it's not a good choice for any system at this point.

> * Please do not add `.idea` to .gitignore, since not all of us use the same IDE. Instead, you can add that directory to your global .gitignore (probably ~/.gitignore). See [this blog post](https://blog.martinhujer.cz/dont-put-idea-vscode-directories-to-projects-gitignore/) for a discussion on the topic.

I'll make this change although I certainly don't agree with that, it only takes one person to forget to do this for those folders to appear in the repository, and I speak for experience with bigger projects, but I'm not really looking for a discussion on this topic :).

As mentioned, I'm not really looking to integrate my changes on this repository because of its unmaintained status, but I'll make those changes if you want to use them in your personal one.

**Comment by dbear496** [comment]
I've been learning CMake and going through the CMakeLists.txt files that you created. So far, they look pretty good. Though unless I've missed something, the install directories on Linux are messed up. As it stands, the lincity-ng binary in installed to ${CMAKE_INSTALL_PREFIX} and read-only data is installed to `${CMAKE_INSTALL_PREFIX}/data`. This is fine on Windows where CMAKE_INSTALL_PREFIX is C:/Program Files/${PROJECT_NAME}. However, on Unix systems,  CMAKE_INSTALL_PREFIX is /usr/local, and this is an awkward place to put an executable and a 'data' directory. On Linux, the binary should go in ${CMAKE_INSTALL_PREFIX}/bin and read-only data should go in ${CMAKE_INSTALL_PREFIX}/share/lincity-ng. I do not know a way to do this in CMake that will work properly on both Windows and Linux besides making a special case for each platform.

**Comment by Arcnor** [comment]
Regarding the directories for Linux, etc... check the docs for `GNUInstallDirs` as well as examples around the Internet, it should fix your issues. Regarding `APPDATADIR` I'm not really sure, I just tested on Windows as mentioned. For the other systems I just defined `DEFAULT_LIBDIR` as `lib` just to make the build happy, but that's probably not the best solution (and maybe you can even use one of the `GNUInstallDirs` variables for that)

**Comment by Arcnor** [comment]
That said, I also feel all that code is just over complicated, and I'm sure could be replaced by a judicious use of SDL functions to find the right paths, even if those have to change, this makes a lot of assumptions about the host platform that might not hold true everywhere, and SDL always has solutions for those under the covers.

**Comment by dbear496** [comment]
Both SDL and PhysFS have a function to get the "base" directory. The documentation is kind of vague about what this actually is, but for both SDL and PhysFS, the source indicates that it is just the directory containing the binary being executed. So if we install the binary to `<prefix>/bin/` and the read-only data to `<prefix>/share/lincity-ng/`, then we could calculate the read-only data directory with `<base dir>/../share/lincity-ng/`.

The reason it worked for you on Windows is you installed the binary and the `data` directory in the same directory (`C:/Program Files/${PROJECT_NAME}/`). So the `data` directory was mounted by PhysFS [here](https://github.com/ReversedGames/lincity-ng/blob/6ed82be68748af453ada5f4d3419db35e5c4d7c2/src/lincity-ng/main.cpp#L141), which, according to the comment, is only supposed to happen when running from the source directory i.e. when it is not installed.

We could use GNUInstallDirs for installing the files, but I don't think it helps with locating the data directory at runtime. We could use GNUInstallDirs to define a header file at configure/compile time with the relevant paths, but this could be wrong if the prefix is changed between compiling and installing.

**Comment by Arcnor** [comment]
Yeah, they have functions for getting a few different paths, but even if it's only getting the executable path, I don't see a problem about putting the data alongside it? The only days you need to be careful about is saves location, and for that there is also a function from SDL, so I think that can be simplified a lot, unless there is some issue I'm not seeing.

**Comment by dbear496** [comment]
On Linux, binaries and read-only data typically go in separate directories. Binaries can go in /usr/local/bin/; this is part of the PATH, and it doesn't make a whole lot of sense to put data in the path. Also, /usr/local/share/ is used for architecture-independent read-only application data, so binaries are not supposed to go there. And in any case, neither the binary nor the data should go directly in /usr/local/.

**Comment by Arcnor** [comment]
Ok, then the game can probably search in that place directly (`/usr/local/share/lincity` or similar) when compiling for Linux, like it's doing now (I think?)

I guess the only missing thing will be adding the correct install paths to CMake, but again, that Gnu macro should work for that, or if it doesn't then you can have a check with a separate section for Linux.

**Comment by dbear496** [comment]
If we use GNUInstallDirs, then things will be installed to the correct places for Linux. On Windows, I think the binary and data would be installed to `C:/Program Files/lincity-ng/bin/` and `C:/Program Files/lincity-ng/share/lincity-ng/` respectively.

**Comment by dbear496** [comment]
Does the installer package a pre-compiled binary? If so, computing the prefix at compile time may be too early. So using `<base dir>/../share/lincity-ng/` is probably the best option.

**Comment by dbear496** [comment]
Would it be reasonable to layout the build folder like the prefix directory, so we don't have to treat running from the project root any different? That is, the binary would be `<project root>/out/bin/lincity-ng`, and the data would go in `<project root>/out/share/lincity-ng/`.

**Comment by Arcnor** [comment]
You can configure CMake to do the right thing depending where you're installing to, although to be honest it's a bit confusing, but basically we can do both.

But for now I think the code as it is right now should work, so maybe add the Gnu stuff first, then the installers can be added at a later date.

Which reminds me, Mac is probably broken as well, as it requires special handling inside CMake to recreate the app bundle, although again, it should probably just work first, then nice packaging 🙂.

**Comment by Arcnor** [comment]
> Would it be reasonable to layout the build folder like the prefix directory, so we don't have to treat running from the project root any different? That is, the binary would be `<project root>/out/bin/lincity-ng`, and the data would go in `<project root>/out/share/lincity-ng/`.

I thought you wanted to keep the structure "standard" on Linux? We can definitely do that though, although I'll just remove the `out` directory from that path.

That said, that's what using the Gnu macro and the normal install targets will do.

**Comment by dbear496** [comment]
I think you misunderstood me. I am making a distinction between running an _installed_ binary and running from the project root. Indeed, I want to layout of the _installation_ to be from GNUInstallDirs; I am only suggesting a change to the project directory structure. It'd probably be more clear if I show you.

**Comment by dbear496** [comment]
Does `lincity_lib` need `LinCity::gui` added as a target link library?

**Comment by dbear496** [comment]
I've incorporated some of your changes into the cmake branch. For now, I'm just getting cmake to work, and I'm waiting to add github actions.

**Comment by eli-schwartz** [comment]
> We could use GNUInstallDirs to define a header file at configure/compile time with the relevant paths, but this could be wrong if the prefix is changed between compiling and installing.

If you are changing the prefix between compiling and installing, then
1. you are doing it wrong
2. the build system should regenerate the define or header, causing source files to be recompiled for the changed options (if it does not do so, then that would have massive fallout such as not properly recompiling when changed dependencies or features are added/removed)



> Does the installer package a pre-compiled binary? If so, computing the prefix at compile time may be too early. So using `<base dir>/../share/lincity-ng/` is probably the best option.

IMHO "computing the prefix" is a red herring :) what you really care about is that there are two different distribution models:
- statically coded install locations (linux distros)
- relocatable install locations (Windows installers)

And when you're building *relocatable* install locations, you don't want to use a prefix, you want to do runtime detection of the relocatable root -- usually based on where the executable is located but up one directory. The actual structure of the relocatable installation should be internally consistent, you don't want this to change between configuring/compiling/installing.

So, you should construct lookup paths via "prefix, followed by data directory", and:
- "prefix" should be either the configure-time prefix, or a runtime construction
- data directory should be hardcoded at configure time

Optionally, either toggle between configure-time prefix / runtime construction via a configure-time option such as `-DRELOCATABLE={ON|OFF}` or else check both and use whichever one succeeds.

**Comment by dbear496** [comment]
I implemented a static install location that is determined at configure time. I'm not really sure the best way to make it relocatable. As you mentioned earlier, the original code that dealt with this was messy, and I believe that was in large part to make it relocatable.

**Comment by dbear496** [comment]
I'm closing this because the reason for this thread is the repo was not maintained, but now I am maintaining it.
