### ISSUE TITLE
./configure failed on M1 Mac

### ISSUE THREAD

**Issue by ilyakava** [lincity-ng/lincity-ng#77]
```
./configure 
checking build system type... configure: error: /bin/sh ./mk/autoconf/config.sub -apple-darwin22.4.0 failed
configure: WARNING: cache variable ac_cv_build contains a newline
```

Are M1 Macs supported?

**Comment by dbear496** [comment]
The build system has recently been migrated from autoconf/jam to cmake, so please update to the latest on the master branch. This may fix your issue. If not, then please open a separate issue.
