### ISSUE TITLE
nerf ports

### ISSUE THREAD

**Issue by dbear496** [lincity-ng/lincity-ng#87]
I always knew that ports were a bit of a cheat. But now I'm realizing that they are **ABSOLUTELY OP**.

As everyone probably already knows, ports can be used to compensate for not really knowing how to win the game. If I don't have enough coal...just import it. *No need to build a mine which comes with the complication of running out of reserves.* If I don't have enough ore...build one mine, and when it is finished, there is a beautiful lake on which to build a port.

But that isn't even the really OP part. If I don't have enough money...fine, just import it. Simply build two ports side-by-side; set one to import coal and export goods and set the other to import goods and export coal. Now, for a simple 200 jobs per day, you get yearly:
- $1.5M in coal taxes
- $6k + $30 per tech in goods taxes
- $19.2k in income taxes
- As much tech production as a single university
- minus $190.8k (max) in net import/export cost

And this scales with more ports. The amount of money is bonkers.

Furthermore, this setup of pairing ports naturally causes commodity inventory to settle at 50%, thus completely eliminating the need to properly balance an economy. And IIRC, a waterfront is only necessary to _build_ a port -- once it is built, the water can be deleted to save space.

So I believe that ports need a nerf. Simply stipulating that they cannot be used in a "sustainable economy" I do not think is enough.

One potential solution is eliminating the tax on coal and goods entering a port. However, this may not fully solve the issue because someone could put coal mines in between the two ports (effectively using the mines as coal transport), so that tax is collected on coal entering the mines. The ports are just used to create very high flow of coal through the mines. Maybe this could be fixed by eliminating tax on commodities entering any construction that it could potentially leave (transport, ports, markets, mines, etc.)

So what does everyone else think? Are ports OP? Do you think they should be nerfed? Do you have any ideas how they could be nerfed?

![Screenshot_20231205_220534](https://github.com/lincity-ng/lincity-ng/assets/70439542/0999118d-6aaf-44a7-8efc-6c841d1a5f76)

**Comment by Mannshoch** [comment]
In real life this means that some company lose money.
One way of using Taxes that may could help here is, if you use it for support your own local production. So such Taxes should only been allowed if you have your own coal mining running.  Taxes are used to steer the use of the imported product. That way you could enhance the lifespan of your coal mine. If you need more money rise the tax and use only own coal and may also sell it. Lower the Tax you do not earn much money but you could run the mine a longer time and earn more money.

The easiest way would be to allow only one Port.

**Comment by Miguelinileugim** [comment]
I would say to limit the number of ports based on population. As in, you need quite a big sized city, enough that potential port revenue would be only a small part of the total economy, before you're allowed to build 1 port. And then any ports after that require higher and higher population (linearly preferably).
