### ISSUE TITLE
Build fails with SDL2 targets not found

### ISSUE THREAD

**Issue by TheGuv** [lincity-ng/lincity-ng#97]
Hello,

I'm trying to bulld the latest 2.9.0 on Linux Mint 21.2 Victoria but failing with

```
$ cmake -B build
-- The CXX compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found SDL2_gfx: /usr/lib/x86_64-linux-gnu/libSDL2_gfx.so (found version "1.0.4") 
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.13") 
-- Found PhysFS: /usr/lib/x86_64-linux-gnu/libphysfs.so  
-- Found LibXslt: /usr/lib/x86_64-linux-gnu/libxslt.so (found version "1.1.34") 
-- Looking for include file dirent.h
-- Looking for include file dirent.h - found
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Configuring done
CMake Error at src/lincity/modules/CMakeLists.txt:77 (target_link_libraries):
  Target "lincity_lib_modules" links to:

    SDL2_image::SDL2_image-static

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

I do have the required libraries installed:

```
$ dpkg --get-selections | grep sdl2
libghc-sdl2-dev			install
libghc-sdl2-ttf-dev		install
libsdl2-2.0-0				install
libsdl2-dev				install
libsdl2-gfx-1.0-0			install
libsdl2-gfx-dev			install
libsdl2-image-2.0-0		install
libsdl2-image-dev		install
libsdl2-mixer-2.0-0		install
libsdl2-mixer-dev			install
libsdl2-ttf-2.0-0			install
libsdl2-ttf-dev			install
```

I think it's a path/naming issue which I tried to read up on using cmake but I'm not a developer and a bit lost now.
Please send the clue bus.

**Comment by dbear496** [comment]
I've run into this issue before. It is an issue with CMake not being able to find a package configuration file for SDL2_image. Usually when you install libsdl2-image-dev, it should add a package configuration file to a location where CMake can find it. The CMake documentation specifies the [naming](https://cmake.org/cmake/help/latest/command/find_package.html) and [location](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure) of these files.

Most package managers are able to list the files installed by a package. Try searching for a file with the `.cmake` extension in the files installed by libsdl2-image-dev. If one exists that matches the CMake package config naming scheme (`*-config.cmake`, `*Config.cmake`, or `Find*.cmake`), then perhaps it was not installed to the correct directory.

If no CMake package configuration file is installed by libsdl2-image-dev, then you can get SDL2 "find module" files from [this GitHub repo](https://github.com/aminosbh/sdl2-cmake-modules). Put the FindSDL2_image.cmake file from this repo into the `mk/cmake/modules/` directory. You will have to modify this file by replacing occurrences of `SDL2::Image` with `SDL2_image::SDL2_image`. Then in the `CMakeLists.txt` file (in the project directory), find the line
```
find_package(SDL2_image CONFIG REQUIRED)
```
and replace it with
```
find_package(SDL2_image REQUIRED)
```

Most of the time when I have had this issue personally, it has been an issue with the *-dev package not being installed properly. But for the few cases where people may need to fall back on a `Find*.cmake` file, I should include all those in the `mk/cmake/modules/` directory.

**Comment by dbear496** [comment]
I would encourage you to figure out why your config files are not being installed properly on your system. But if you want to fall back on find modules, then you can checkout the `sdl2-find-modules` branch from my fork: https://github.com/dbear496/lincity-ng/tree/sdl2-find-modules.

**Comment by TheGuv** [comment]
Thank you for the help!

It turns out that although the *Debian* package of libsdl2-image-dev has the cmake files, the *Ubuntu* package (which Mint is based on) does not. The libsdl2-mixer-dev and libsdl2-ttf-dev packages are also lacking.

The easy option to test was to downloaded the Debian versions and manually install the missing files. It built fine.

I hade problems with installing due to the installer trying to copy files (e.g. COPYING) from the data dir whereas they appear to be in the root. There were also problems running the installed version but running from the build dir worked fine. Would you like me to open new issues for those or?

**Comment by dbear496** [comment]
Glad you got it to build.

Thanks for bringing these two other bugs to my attention. I was able to replicate the first one where COPYING is not in the expected place, and I have a fix in the works. The second issue I was not able to replicate based on your brief mention, so I encourage you to open a new issue for that.
